
package soa.ws.hello.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "hola", targetNamespace = "http://sw/", wsdlLocation = "http://chalo-pc:8080/HolaMundo/hola?WSDL")
public class Hola_Service
    extends Service
{

    private final static URL HOLA_WSDL_LOCATION;
    private final static WebServiceException HOLA_EXCEPTION;
    private final static QName HOLA_QNAME = new QName("http://sw/", "hola");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://chalo-pc:8080/HolaMundo/hola?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOLA_WSDL_LOCATION = url;
        HOLA_EXCEPTION = e;
    }

    public Hola_Service() {
        super(__getWsdlLocation(), HOLA_QNAME);
    }

    public Hola_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOLA_QNAME, features);
    }

    public Hola_Service(URL wsdlLocation) {
        super(wsdlLocation, HOLA_QNAME);
    }

    public Hola_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOLA_QNAME, features);
    }

    public Hola_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Hola_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Hola
     */
    @WebEndpoint(name = "HolaPort")
    public Hola getHolaPort() {
        return super.getPort(new QName("http://sw/", "HolaPort"), Hola.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Hola
     */
    @WebEndpoint(name = "HolaPort")
    public Hola getHolaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sw/", "HolaPort"), Hola.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOLA_EXCEPTION!= null) {
            throw HOLA_EXCEPTION;
        }
        return HOLA_WSDL_LOCATION;
    }

}
