
package soa.ws.hello.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hola", targetNamespace = "http://sw/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hola {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://sw/", className = "soa.ws.hello.stub.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://sw/", className = "soa.ws.hello.stub.HelloResponse")
    @Action(input = "http://sw/Hola/helloRequest", output = "http://sw/Hola/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
